-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBscWZ5zKS6mZGoA4
WT10elYHBJqTNnM0+yqAJSvLZhKgCgYIKoZIzj0DAQehRANCAAREQorwJbhPNXHD
0fmrKAR2rcFEduK5/56j+fuoiobSEqieZO/HbXEVmN7bkJyw3QXqm55VTrs38OX1
5EfrCUPi
-----END PRIVATE KEY-----